-- Editable words, prices, and Service-media filenames.
-- The public site can read these rows. Writes stay in the Supabase dashboard.

create table if not exists public.site_copy (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

comment on table public.site_copy is
  'Public site wording and Service-media filenames. Edit value in the Table Editor.';

alter table public.site_copy enable row level security;

grant select on table public.site_copy to anon, authenticated;
revoke insert, update, delete on table public.site_copy from anon, authenticated;

drop policy if exists site_copy_read on public.site_copy;
create policy site_copy_read
  on public.site_copy
  for select
  to anon, authenticated
  using (true);

create or replace function public.touch_site_copy()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists site_copy_updated on public.site_copy;
create trigger site_copy_updated
  before update on public.site_copy
  for each row
  execute function public.touch_site_copy();

insert into public.site_copy (key, value)
values
  ($copy$media.hero$copy$, $copy$Hero.MP4$copy$),
  ($copy$media.aerial-video$copy$, $copy$Funrun.MP4$copy$),
  ($copy$media.real-estate-drone-photography$copy$, $copy$Realestate.MP4$copy$),
  ($copy$media.drone-inspections$copy$, $copy$Inspection.MP4$copy$),
  ($copy$media.event-highlights$copy$, $copy$Show.MP4$copy$),
  ($copy$media.full-day-event-coverage$copy$, $copy$Races.MP4$copy$),
  ($copy$media.something-else$copy$, $copy$Rafts.MP4$copy$),
  ($copy$nav.about$copy$, $copy$About$copy$),
  ($copy$nav.services$copy$, $copy$Services$copy$),
  ($copy$nav.work$copy$, $copy$Our work$copy$),
  ($copy$nav.quote$copy$, $copy$Build a quote$copy$),
  ($copy$nav.pricing$copy$, $copy$Pricing$copy$),
  ($copy$footer.abn$copy$, $copy$ABN 41910833513$copy$),
  ($copy$footer.line$copy$, $copy$Uncover a different perspective.$copy$),
  ($copy$home.about.heading$copy$, $copy$What we do$copy$),
  ($copy$home.about.sub$copy$, $copy$Filmed in the region we live in.$copy$),
  ($copy$home.about.note$copy$, $copy$A locally owned videography and aerial imaging business in the Gladstone Region. A two-person crew films the big picture and the moments inside it — events, people, property and places — from the ground and from the air.$copy$),
  ($copy$home.card.aerial-video.title$copy$, $copy$Aerial Video$copy$),
  ($copy$home.card.aerial-video.line$copy$, $copy$One flight. A range of angles. The footage, unedited.$copy$),
  ($copy$home.card.real-estate-drone-photography.title$copy$, $copy$Real Estate$copy$),
  ($copy$home.card.real-estate-drone-photography.line$copy$, $copy$The house, the block, and the setting around it.$copy$),
  ($copy$home.card.drone-inspections.title$copy$, $copy$Inspections$copy$),
  ($copy$home.card.drone-inspections.line$copy$, $copy$Roofs, solar, sheds and tanks, seen from above.$copy$),
  ($copy$home.card.event-highlights.title$copy$, $copy$Event Highlights$copy$),
  ($copy$home.card.event-highlights.line$copy$, $copy$One film of the people, the atmosphere, the day.$copy$),
  ($copy$home.card.full-day-event-coverage.title$copy$, $copy$Full Day$copy$),
  ($copy$home.card.full-day-event-coverage.line$copy$, $copy$A two-person crew, on site for the whole event.$copy$),
  ($copy$home.card.something-else.title$copy$, $copy$Something Else$copy$),
  ($copy$home.card.something-else.line$copy$, $copy$A job that doesn’t sit in the other packages.$copy$),
  ($copy$home.card.something-else.price$copy$, $copy$We’ll confirm$copy$),
  ($copy$home.action.learn$copy$, $copy$Learn more$copy$),
  ($copy$home.action.book$copy$, $copy$Book$copy$),
  ($copy$home.showreel.label$copy$, $copy$Our work$copy$),
  ($copy$home.showreel.title$copy$, $copy$Recent reels.$copy$),
  ($copy$home.showreel.seeAll$copy$, $copy$See all on Facebook$copy$),
  ($copy$service.aerial-video.title$copy$, $copy$Aerial Video$copy$),
  ($copy$service.aerial-video.line$copy$, $copy$Unedited aerial footage from a single flight.$copy$),
  ($copy$service.aerial-video.includedHeading$copy$, $copy$What’s included$copy$),
  ($copy$service.aerial-video.note.0$copy$, $copy$Aerial video for an event, business, product, or location. One flight captures a range of clips and angles. You receive the unedited footage to edit, share, or archive.$copy$),
  ($copy$service.aerial-video.note.1$copy$, $copy$The starting price covers a single flight in Gladstone, Boyne Island, Tannum Sands, or Calliope. Additional flight time, a second drone, and faster delivery can be added when you build the package.$copy$),
  ($copy$service.aerial-video.point.0$copy$, $copy$One drone flight, approximately 25–30 minutes$copy$),
  ($copy$service.aerial-video.point.1$copy$, $copy$Multiple clips from a range of angles$copy$),
  ($copy$service.aerial-video.point.2$copy$, $copy$Unedited footage, ready to use$copy$),
  ($copy$service.aerial-video.point.3$copy$, $copy$Delivered by a private cloud link$copy$),
  ($copy$service.real-estate-drone-photography.title$copy$, $copy$Real Estate$copy$),
  ($copy$service.real-estate-drone-photography.line$copy$, $copy$Aerial photographs of the property and its setting.$copy$),
  ($copy$service.real-estate-drone-photography.includedHeading$copy$, $copy$What’s included$copy$),
  ($copy$service.real-estate-drone-photography.note.0$copy$, $copy$Aerial photographs for a home, block of land, or commercial property. The images show the property and its setting from angles that are not possible from the ground, prepared for a listing, brochure, or social media.$copy$),
  ($copy$service.real-estate-drone-photography.note.1$copy$, $copy$The starting price covers five edited photographs of a residential property, vacant land, or a small commercial site in Gladstone, Boyne Island, Tannum Sands, or Calliope. Larger properties and additional photographs are priced in the package.$copy$),
  ($copy$service.real-estate-drone-photography.point.0$copy$, $copy$Five edited, high-resolution photographs$copy$),
  ($copy$service.real-estate-drone-photography.point.1$copy$, $copy$The property and its immediate setting$copy$),
  ($copy$service.real-estate-drone-photography.point.2$copy$, $copy$Prepared for listings, marketing, and social media$copy$),
  ($copy$service.real-estate-drone-photography.point.3$copy$, $copy$Delivered within 5 business days, weather permitting$copy$),
  ($copy$service.drone-inspections.title$copy$, $copy$Inspections$copy$),
  ($copy$service.drone-inspections.line$copy$, $copy$A visual record of roofs, solar, and structures from above.$copy$),
  ($copy$service.drone-inspections.includedHeading$copy$, $copy$What’s included$copy$),
  ($copy$service.drone-inspections.note.0$copy$, $copy$A visual inspection of a roof, solar array, shed, tank, carport, or other structure that is difficult to reach. The flight records what can be seen from above, including damage, repairs, and areas that need maintenance, without placing anyone at height.$copy$),
  ($copy$service.drone-inspections.note.1$copy$, $copy$This is a visual record, not a structural or engineering report. The starting price covers one site in Gladstone, Boyne Island, Tannum Sands, or Calliope.$copy$),
  ($copy$service.drone-inspections.point.0$copy$, $copy$Photographs and video of the area you nominate$copy$),
  ($copy$service.drone-inspections.point.1$copy$, $copy$Roofs, solar panels, sheds, tanks, and carports$copy$),
  ($copy$service.drone-inspections.point.2$copy$, $copy$Visible damage, repairs, and maintenance areas$copy$),
  ($copy$service.drone-inspections.point.3$copy$, $copy$Completed without unnecessary access at height$copy$),
  ($copy$service.event-highlights.title$copy$, $copy$Event Highlights$copy$),
  ($copy$service.event-highlights.line$copy$, $copy$A short film of the event, from the ground and the air.$copy$),
  ($copy$service.event-highlights.includedHeading$copy$, $copy$What’s included$copy$),
  ($copy$service.event-highlights.note.0$copy$, $copy$A short film of your event, filmed from the ground and the air. A two-person crew covers the guests, the atmosphere, and the moments worth keeping, then edits them into one highlight for social media.$copy$),
  ($copy$service.event-highlights.note.1$copy$, $copy$Coverage is up to 2 hours. Celebrations, sport, and community events in Gladstone, Boyne Island, Tannum Sands, or Calliope start at this price. Additional video, more time on the ground, or a second flight can be added in the package.$copy$),
  ($copy$service.event-highlights.point.0$copy$, $copy$Up to 2 hours on site$copy$),
  ($copy$service.event-highlights.point.1$copy$, $copy$Two-person crew$copy$),
  ($copy$service.event-highlights.point.2$copy$, $copy$Approximately 1 hour of ground coverage$copy$),
  ($copy$service.event-highlights.point.3$copy$, $copy$Guest interaction and the atmosphere of the event$copy$),
  ($copy$service.event-highlights.point.4$copy$, $copy$One drone flight, approximately 25 minutes$copy$),
  ($copy$service.event-highlights.point.5$copy$, $copy$Professional editing$copy$),
  ($copy$service.event-highlights.point.6$copy$, $copy$One social highlight, approximately 30–90 seconds$copy$),
  ($copy$service.full-day-event-coverage.title$copy$, $copy$Full Day$copy$),
  ($copy$service.full-day-event-coverage.line$copy$, $copy$A two-person crew on site for the full event.$copy$),
  ($copy$service.full-day-event-coverage.includedHeading$copy$, $copy$What’s included$copy$),
  ($copy$service.full-day-event-coverage.note.0$copy$, $copy$Coverage for an event that needs more than a single highlight. A two-person crew remains on site for up to 5 hours, filming from the ground throughout and from the air across up to three flights.$copy$),
  ($copy$service.full-day-event-coverage.note.1$copy$, $copy$You receive three edited social reels and a catalogue of additional clips to use after the day. Live reels during the event, extra hours, and extra flights can be added in the package.$copy$),
  ($copy$service.full-day-event-coverage.point.0$copy$, $copy$Up to 5 hours of event coverage$copy$),
  ($copy$service.full-day-event-coverage.point.1$copy$, $copy$Two-person crew$copy$),
  ($copy$service.full-day-event-coverage.point.2$copy$, $copy$Ground filming throughout$copy$),
  ($copy$service.full-day-event-coverage.point.3$copy$, $copy$Up to 3 drone flights, approximately 25 minutes each$copy$),
  ($copy$service.full-day-event-coverage.point.4$copy$, $copy$3 edited social reels, approximately 30–90 seconds each$copy$),
  ($copy$service.full-day-event-coverage.point.5$copy$, $copy$A catalogue of additional unedited clips$copy$),
  ($copy$service.full-day-event-coverage.point.6$copy$, $copy$Professional editing and delivery$copy$),
  ($copy$pricing.eyebrow$copy$, $copy$Pricing$copy$),
  ($copy$pricing.heading$copy$, $copy$Scoped to your project — not a one-size package.$copy$),
  ($copy$pricing.intro$copy$, $copy$Rather than offering the same package to every client, we establish what you need, how the content will be used and when it needs to be delivered. Then we provide a clear quote.$copy$),
  ($copy$pricing.card.0.title$copy$, $copy$Single project$copy$),
  ($copy$pricing.card.0.label$copy$, $copy$Quote on enquiry$copy$),
  ($copy$pricing.card.0.text$copy$, $copy$Ideal for a one-off shoot — a highlight film, commercial video, aerial videography or specialist real estate / inspection imagery.$copy$),
  ($copy$pricing.card.0.point.0$copy$, $copy$Scoped to location and duration$copy$),
  ($copy$pricing.card.0.point.1$copy$, $copy$Ground and/or aerial capture$copy$),
  ($copy$pricing.card.0.point.2$copy$, $copy$Agreed deliverables and timeline$copy$),
  ($copy$pricing.card.0.point.3$copy$, $copy$Digital delivery ready to publish$copy$),
  ($copy$pricing.card.0.button$copy$, $copy$Request a quote$copy$),
  ($copy$pricing.card.1.title$copy$, $copy$Events & live content$copy$),
  ($copy$pricing.card.1.label$copy$, $copy$Quote on enquiry$copy$),
  ($copy$pricing.card.1.text$copy$, $copy$Coverage for festivals, sport, corporate functions and regional events — including rapid-turnaround social content where required.$copy$),
  ($copy$pricing.card.1.point.0$copy$, $copy$Half-day or full-day coverage$copy$),
  ($copy$pricing.card.1.point.1$copy$, $copy$Optional live event content$copy$),
  ($copy$pricing.card.1.point.2$copy$, $copy$Highlight film and social cutdowns$copy$),
  ($copy$pricing.card.1.point.3$copy$, $copy$Can combine ground + drone$copy$),
  ($copy$pricing.card.1.button$copy$, $copy$Request a quote$copy$),
  ($copy$pricing.card.2.title$copy$, $copy$Commercial & aerial$copy$),
  ($copy$pricing.card.2.label$copy$, $copy$Quote on enquiry$copy$),
  ($copy$pricing.card.2.text$copy$, $copy$Brand films, project showcases and aerial videography for commercial and industrial clients — plus specialist aerial photography for property and inspections.$copy$),
  ($copy$pricing.card.2.point.0$copy$, $copy$Commercial video production$copy$),
  ($copy$pricing.card.2.point.1$copy$, $copy$Aerial videography$copy$),
  ($copy$pricing.card.2.point.2$copy$, $copy$Specialist aerial photography$copy$),
  ($copy$pricing.card.2.point.3$copy$, $copy$Scoped to site and approvals$copy$),
  ($copy$pricing.card.2.button$copy$, $copy$Request a quote$copy$),
  ($copy$pricing.note$copy$, $copy$Service availability and drone operations are subject to project scope, site permissions and applicable aviation approvals.$copy$),
  ($copy$quote.chrome.heading$copy$, $copy$Build Your Package$copy$),
  ($copy$quote.chrome.chooseService$copy$, $copy$Choose a service$copy$),
  ($copy$quote.chrome.chooseHint$copy$, $copy$What would you like us to create?$copy$),
  ($copy$quote.chrome.somethingElse$copy$, $copy$Something Else$copy$),
  ($copy$quote.chrome.somethingElseDetail$copy$, $copy$A job that doesn’t sit in the other packages.$copy$),
  ($copy$quote.chrome.emailUs$copy$, $copy$Email us$copy$),
  ($copy$quote.chrome.from$copy$, $copy$From$copy$),
  ($copy$quote.chrome.startingAt$copy$, $copy$Starting at$copy$),
  ($copy$quote.chrome.startingFrom$copy$, $copy$Starting from$copy$),
  ($copy$quote.chrome.includedHeading$copy$, $copy$What’s included$copy$),
  ($copy$quote.chrome.included$copy$, $copy$Included$copy$),
  ($copy$quote.chrome.confirm$copy$, $copy$We'll confirm$copy$),
  ($copy$quote.chrome.yourQuote$copy$, $copy$Your quote$copy$),
  ($copy$quote.chrome.whoTitle$copy$, $copy$Who are you.$copy$),
  ($copy$quote.chrome.whoHint$copy$, $copy$Your name, email and phone, so we can send the quote back.$copy$),
  ($copy$quote.chrome.whenTitle$copy$, $copy$When and where.$copy$),
  ($copy$quote.chrome.whenHint$copy$, $copy$Tell us when and where our services are needed.$copy$),
  ($copy$quote.chrome.tellUsMore$copy$, $copy$Tell us more$copy$),
  ($copy$quote.chrome.morePlaceholder$copy$, $copy$Anything else we should know$copy$),
  ($copy$quote.chrome.name$copy$, $copy$Name$copy$),
  ($copy$quote.chrome.email$copy$, $copy$Email$copy$),
  ($copy$quote.chrome.phone$copy$, $copy$Phone$copy$),
  ($copy$quote.chrome.address$copy$, $copy$Address$copy$),
  ($copy$quote.chrome.date$copy$, $copy$Event date$copy$),
  ($copy$quote.chrome.time$copy$, $copy$Event time$copy$),
  ($copy$quote.chrome.continue$copy$, $copy$Continue$copy$),
  ($copy$quote.chrome.send$copy$, $copy$Send quote$copy$),
  ($copy$quote.chrome.sending$copy$, $copy$Sending…$copy$),
  ($copy$quote.chrome.sent$copy$, $copy$Quote sent$copy$),
  ($copy$quote.chrome.sentNote$copy$, $copy$Quote sent. We’ll reply by email.$copy$),
  ($copy$quote.chrome.chooseOne$copy$, $copy$Choose a service.$copy$),
  ($copy$quote.chrome.acceptAll$copy$, $copy$Accept each point to send the quote.$copy$),
  ($copy$quote.chrome.missingDetail$copy$, $copy$Add the missing detail.$copy$),
  ($copy$quote.chrome.invalidContact$copy$, $copy$Add your name and a valid email.$copy$),
  ($copy$quote.chrome.missingPhone$copy$, $copy$Add a phone number.$copy$),
  ($copy$quote.chrome.missingWhen$copy$, $copy$Add the event date and time.$copy$),
  ($copy$quote.chrome.missingAddress$copy$, $copy$Add the address.$copy$),
  ($copy$quote.chrome.emailUnavailable$copy$, $copy$Email isn’t set up yet.$copy$),
  ($copy$quote.chrome.sendFailed$copy$, $copy$Couldn’t send the quote. Try again in a moment.$copy$),
  ($copy$quote.aerial-video.title$copy$, $copy$Aerial Video$copy$),
  ($copy$quote.aerial-video.summary$copy$, $copy$Film an event, business, product or location from the air. You receive the unedited footage.$copy$),
  ($copy$quote.aerial-video.baseLabel$copy$, $copy$One drone flight$copy$),
  ($copy$quote.aerial-video.baseDetail$copy$, $copy$About 25–30 minutes$copy$),
  ($copy$quote.aerial-video.basePrice$copy$, $copy$120$copy$),
  ($copy$quote.aerial-video.overview.0$copy$, $copy$One drone flight, approximately 25–30 minutes$copy$),
  ($copy$quote.aerial-video.overview.1$copy$, $copy$Multiple clips from a range of angles$copy$),
  ($copy$quote.aerial-video.overview.2$copy$, $copy$Unedited footage, ready to use$copy$),
  ($copy$quote.aerial-video.overview.3$copy$, $copy$Delivered by a private cloud link$copy$),
  ($copy$quote.aerial-video.location.title$copy$, $copy$Location$copy$),
  ($copy$quote.aerial-video.location.hint$copy$, $copy$Where is the flight?$copy$),
  ($copy$quote.aerial-video.location.gladstone.label$copy$, $copy$Gladstone$copy$),
  ($copy$quote.aerial-video.location.boyne.label$copy$, $copy$Boyne Island / Tannum Sands$copy$),
  ($copy$quote.aerial-video.location.calliope.label$copy$, $copy$Calliope$copy$),
  ($copy$quote.aerial-video.location.agnes.label$copy$, $copy$Agnes Water / 1770$copy$),
  ($copy$quote.aerial-video.location.agnes.price$copy$, $copy$100$copy$),
  ($copy$quote.aerial-video.location.other.label$copy$, $copy$Other$copy$),
  ($copy$quote.aerial-video.location.other.inputLabel$copy$, $copy$Location$copy$),
  ($copy$quote.aerial-video.location.other.note$copy$, $copy$We'll confirm$copy$),
  ($copy$quote.aerial-video.event.title$copy$, $copy$Event$copy$),
  ($copy$quote.aerial-video.event.hint$copy$, $copy$What kind of event is it?$copy$),
  ($copy$quote.aerial-video.event.outdoor.label$copy$, $copy$Outdoor Function$copy$),
  ($copy$quote.aerial-video.event.outdoor.detail$copy$, $copy$Christmas party, ladies day, birthdays and similar.$copy$),
  ($copy$quote.aerial-video.event.indoor.label$copy$, $copy$Indoor Function$copy$),
  ($copy$quote.aerial-video.event.indoor.note$copy$, $copy$Enquire$copy$),
  ($copy$quote.aerial-video.event.sport.label$copy$, $copy$Sport Event$copy$),
  ($copy$quote.aerial-video.event.sport.detail$copy$, $copy$Football game, sport carnival, fun run and similar.$copy$),
  ($copy$quote.aerial-video.event.community.label$copy$, $copy$Community Event$copy$),
  ($copy$quote.aerial-video.event.community.detail$copy$, $copy$Markets, fairs, shows and similar.$copy$),
  ($copy$quote.aerial-video.event.other.label$copy$, $copy$Something Else$copy$),
  ($copy$quote.aerial-video.event.other.inputLabel$copy$, $copy$What is it?$copy$),
  ($copy$quote.aerial-video.event.other.inputError$copy$, $copy$Tell us what the event is to continue.$copy$),
  ($copy$quote.aerial-video.event.other.note$copy$, $copy$Enquire$copy$),
  ($copy$quote.aerial-video.addons.title$copy$, $copy$Add-ons$copy$),
  ($copy$quote.aerial-video.addons.hint$copy$, $copy$Optional. Extra flight time is one choice or the other, and so is the cloud-link turnaround.$copy$),
  ($copy$quote.aerial-video.addons.flight-30.label$copy$, $copy$Additional Flight$copy$),
  ($copy$quote.aerial-video.addons.flight-30.detail$copy$, $copy$+30 minutes$copy$),
  ($copy$quote.aerial-video.addons.flight-30.price$copy$, $copy$50$copy$),
  ($copy$quote.aerial-video.addons.flight-60.label$copy$, $copy$Two Additional Flights$copy$),
  ($copy$quote.aerial-video.addons.flight-60.detail$copy$, $copy$+60 minutes$copy$),
  ($copy$quote.aerial-video.addons.flight-60.price$copy$, $copy$100$copy$),
  ($copy$quote.aerial-video.addons.second-drone.label$copy$, $copy$Additional Drone And Operator$copy$),
  ($copy$quote.aerial-video.addons.second-drone.detail$copy$, $copy$Includes an additional flight.$copy$),
  ($copy$quote.aerial-video.addons.second-drone.price$copy$, $copy$120$copy$),
  ($copy$quote.aerial-video.addons.same-day.label$copy$, $copy$Footage Delivered On The Day$copy$),
  ($copy$quote.aerial-video.addons.same-day.detail$copy$, $copy$Cloud link$copy$),
  ($copy$quote.aerial-video.addons.same-day.price$copy$, $copy$50$copy$),
  ($copy$quote.aerial-video.addons.within-24.label$copy$, $copy$Footage Delivered Within 24 Hours$copy$),
  ($copy$quote.aerial-video.addons.within-24.detail$copy$, $copy$Cloud link$copy$),
  ($copy$quote.aerial-video.addons.within-24.price$copy$, $copy$20$copy$),
  ($copy$quote.aerial-video.addons.usb.label$copy$, $copy$Footage Delivered On USB$copy$),
  ($copy$quote.aerial-video.addons.usb.price$copy$, $copy$30$copy$),
  ($copy$quote.aerial-video.acknowledgements.title$copy$, $copy$Acknowledgements$copy$),
  ($copy$quote.aerial-video.acknowledgements.hint$copy$, $copy$Accept each point to continue.$copy$),
  ($copy$quote.aerial-video.acknowledgements.flight-rules.label$copy$, $copy$Flight Rules & Safety$copy$),
  ($copy$quote.aerial-video.acknowledgements.flight-rules.detail$copy$, $copy$I understand all flights are subject to CASA regulations, airspace restrictions, site conditions and the pilot’s safety assessment. Safety and legal requirements take priority over requested shots or flight paths.$copy$),
  ($copy$quote.aerial-video.acknowledgements.weather.label$copy$, $copy$Weather & Footage Quality$copy$),
  ($copy$quote.aerial-video.acknowledgements.weather.detail$copy$, $copy$I understand weather, wind, lighting, visibility and other environmental conditions may affect the flight and footage quality. Flights may be modified, postponed or cancelled where conditions are unsafe or unsuitable.$copy$),
  ($copy$quote.aerial-video.acknowledgements.access.label$copy$, $copy$Access & Permission$copy$),
  ($copy$quote.aerial-video.acknowledgements.access.detail$copy$, $copy$I confirm I have appropriate permission for the requested location and filming. I understand that people, crowds, property access and site hazards may restrict where the drone can legally and safely operate.$copy$),
  ($copy$quote.aerial-video.acknowledgements.booking.label$copy$, $copy$Booking, Cancellations & Refunds$copy$),
  ($copy$quote.aerial-video.acknowledgements.booking.detail$copy$, $copy$I understand a 20% deposit is required to confirm the booking and 48 hours’ notice is required for cancellation or rescheduling. Late cancellations may result in loss of the deposit. Flights unable to proceed due to weather, safety, legal restrictions or unsuitable filming conditions may be rescheduled or refunded where appropriate.$copy$),
  ($copy$quote.real-estate-drone-photography.title$copy$, $copy$Real Estate Drone Photography$copy$),
  ($copy$quote.real-estate-drone-photography.summary$copy$, $copy$Photographs of a home, block of land or commercial property for a listing, brochure or social media.$copy$),
  ($copy$quote.real-estate-drone-photography.baseLabel$copy$, $copy$Five photographs$copy$),
  ($copy$quote.real-estate-drone-photography.baseDetail$copy$, $copy$Within 5 business days, weather allowing$copy$),
  ($copy$quote.real-estate-drone-photography.basePrice$copy$, $copy$150$copy$),
  ($copy$quote.real-estate-drone-photography.overview.0$copy$, $copy$Five edited, high-resolution photographs$copy$),
  ($copy$quote.real-estate-drone-photography.overview.1$copy$, $copy$The property and its immediate setting$copy$),
  ($copy$quote.real-estate-drone-photography.overview.2$copy$, $copy$Prepared for listings, marketing and social media$copy$),
  ($copy$quote.real-estate-drone-photography.overview.3$copy$, $copy$Delivered within 5 business days, weather permitting$copy$),
  ($copy$quote.real-estate-drone-photography.finish.type$copy$, $copy$payment$copy$),
  ($copy$quote.real-estate-drone-photography.finish.venueLabel$copy$, $copy$Location of the property$copy$),
  ($copy$quote.real-estate-drone-photography.finish.venueError$copy$, $copy$property location$copy$),
  ($copy$quote.real-estate-drone-photography.finish.dateLabel$copy$, $copy$Date of the shoot$copy$),
  ($copy$quote.real-estate-drone-photography.finish.dateError$copy$, $copy$date of the shoot$copy$),
  ($copy$quote.real-estate-drone-photography.finish.timeLabel$copy$, $copy$Time we should arrive$copy$),
  ($copy$quote.real-estate-drone-photography.finish.messageLabel$copy$, $copy$What should we photograph?$copy$),
  ($copy$quote.real-estate-drone-photography.finish.messageHeading$copy$, $copy$What should we photograph?$copy$),
  ($copy$quote.real-estate-drone-photography.location.title$copy$, $copy$Location$copy$),
  ($copy$quote.real-estate-drone-photography.location.hint$copy$, $copy$Where is the property?$copy$),
  ($copy$quote.real-estate-drone-photography.location.gladstone.label$copy$, $copy$Gladstone$copy$),
  ($copy$quote.real-estate-drone-photography.location.boyne.label$copy$, $copy$Boyne Island / Tannum Sands$copy$),
  ($copy$quote.real-estate-drone-photography.location.calliope.label$copy$, $copy$Calliope$copy$),
  ($copy$quote.real-estate-drone-photography.location.agnes.label$copy$, $copy$Agnes Water / 1770$copy$),
  ($copy$quote.real-estate-drone-photography.location.agnes.price$copy$, $copy$100$copy$),
  ($copy$quote.real-estate-drone-photography.location.other.label$copy$, $copy$Other$copy$),
  ($copy$quote.real-estate-drone-photography.location.other.inputLabel$copy$, $copy$Location$copy$),
  ($copy$quote.real-estate-drone-photography.location.other.note$copy$, $copy$We'll confirm$copy$),
  ($copy$quote.real-estate-drone-photography.property.title$copy$, $copy$Property type$copy$),
  ($copy$quote.real-estate-drone-photography.property.hint$copy$, $copy$What kind of property is it?$copy$),
  ($copy$quote.real-estate-drone-photography.property.residential.label$copy$, $copy$Residential$copy$),
  ($copy$quote.real-estate-drone-photography.property.vacant.label$copy$, $copy$Vacant Land$copy$),
  ($copy$quote.real-estate-drone-photography.property.small-commercial.label$copy$, $copy$Small Commercial$copy$),
  ($copy$quote.real-estate-drone-photography.property.small-commercial.detail$copy$, $copy$Cafe, office space, shopfront.$copy$),
  ($copy$quote.real-estate-drone-photography.property.acreage.label$copy$, $copy$Acreage$copy$),
  ($copy$quote.real-estate-drone-photography.property.acreage.detail$copy$, $copy$1 acre up to 1 hectare.$copy$),
  ($copy$quote.real-estate-drone-photography.property.acreage.price$copy$, $copy$70$copy$),
  ($copy$quote.real-estate-drone-photography.property.rural.label$copy$, $copy$Rural$copy$),
  ($copy$quote.real-estate-drone-photography.property.rural.detail$copy$, $copy$1 hectare and above.$copy$),
  ($copy$quote.real-estate-drone-photography.property.rural.price$copy$, $copy$100$copy$),
  ($copy$quote.real-estate-drone-photography.property.medium-commercial.label$copy$, $copy$Medium Commercial$copy$),
  ($copy$quote.real-estate-drone-photography.property.medium-commercial.detail$copy$, $copy$Industrial sheds, petrol stations, standalone building.$copy$),
  ($copy$quote.real-estate-drone-photography.property.medium-commercial.price$copy$, $copy$50$copy$),
  ($copy$quote.real-estate-drone-photography.property.large-commercial.label$copy$, $copy$Large Commercial And Industrial$copy$),
  ($copy$quote.real-estate-drone-photography.property.large-commercial.detail$copy$, $copy$Shopping centres, industrial complex, multiple buildings or sheds.$copy$),
  ($copy$quote.real-estate-drone-photography.property.large-commercial.price$copy$, $copy$100$copy$),
  ($copy$quote.real-estate-drone-photography.addons.title$copy$, $copy$Add-ons$copy$),
  ($copy$quote.real-estate-drone-photography.addons.hint$copy$, $copy$Optional. Urgent delivery turns off the other add-ons, except additional photographs.$copy$),
  ($copy$quote.real-estate-drone-photography.addons.photos-10.label$copy$, $copy$Additional 10 Photographs$copy$),
  ($copy$quote.real-estate-drone-photography.addons.photos-10.price$copy$, $copy$30$copy$),
  ($copy$quote.real-estate-drone-photography.addons.ocean.label$copy$, $copy$Include Nearby Ocean Or River$copy$),
  ($copy$quote.real-estate-drone-photography.addons.ocean.price$copy$, $copy$20$copy$),
  ($copy$quote.real-estate-drone-photography.addons.high-tide.label$copy$, $copy$On High Tide$copy$),
  ($copy$quote.real-estate-drone-photography.addons.high-tide.price$copy$, $copy$30$copy$),
  ($copy$quote.real-estate-drone-photography.addons.golden-hour.label$copy$, $copy$Golden Hour$copy$),
  ($copy$quote.real-estate-drone-photography.addons.golden-hour.detail$copy$, $copy$Sunrise or sunset.$copy$),
  ($copy$quote.real-estate-drone-photography.addons.golden-hour.price$copy$, $copy$50$copy$),
  ($copy$quote.real-estate-drone-photography.addons.landmarks.label$copy$, $copy$Distant Aerial Shot With Edited Labels Of Landmarks Nearby$copy$),
  ($copy$quote.real-estate-drone-photography.addons.landmarks.price$copy$, $copy$50$copy$),
  ($copy$quote.real-estate-drone-photography.addons.urgent.label$copy$, $copy$Urgent$copy$),
  ($copy$quote.real-estate-drone-photography.addons.urgent.detail$copy$, $copy$24 hour delivery.$copy$),
  ($copy$quote.real-estate-drone-photography.addons.urgent.price$copy$, $copy$125$copy$),
  ($copy$quote.real-estate-drone-photography.acknowledgements.title$copy$, $copy$Acknowledgements$copy$),
  ($copy$quote.real-estate-drone-photography.acknowledgements.hint$copy$, $copy$Accept each point to continue.$copy$),
  ($copy$quote.real-estate-drone-photography.acknowledgements.flight-rules.label$copy$, $copy$Flight Rules & Safety$copy$),
  ($copy$quote.real-estate-drone-photography.acknowledgements.flight-rules.detail$copy$, $copy$I understand all drone photography is subject to CASA regulations, airspace restrictions and the pilot’s safety assessment. These requirements may limit the height, position or angles available when photographing the property.$copy$),
  ($copy$quote.real-estate-drone-photography.acknowledgements.weather.label$copy$, $copy$Weather & Photo Quality$copy$),
  ($copy$quote.real-estate-drone-photography.acknowledgements.weather.detail$copy$, $copy$I understand weather, wind, lighting, shadows, glare, haze and other conditions may affect the appearance of the property. Photography may be postponed or rescheduled if conditions are unsafe or unlikely to produce suitable images.$copy$),
  ($copy$quote.real-estate-drone-photography.acknowledgements.access.label$copy$, $copy$Property Access & Permission$copy$),
  ($copy$quote.real-estate-drone-photography.acknowledgements.access.detail$copy$, $copy$I confirm I have permission for the property to be photographed and for Gladstone Uncovered to access the nominated location where required. I understand neighbouring properties, people, roads, obstacles and other site conditions may restrict available photographs.$copy$),
  ($copy$quote.real-estate-drone-photography.acknowledgements.booking.label$copy$, $copy$Booking, Cancellations & Refunds$copy$),
  ($copy$quote.real-estate-drone-photography.acknowledgements.booking.detail$copy$, $copy$I understand a 20% deposit is required to confirm the booking and 48 hours’ notice is required for cancellation or rescheduling. Late cancellations may result in loss of the deposit. If photography cannot proceed due to weather, safety, legal restrictions or unsuitable conditions, the service may be rescheduled or refunded where appropriate.$copy$),
  ($copy$quote.drone-inspections.title$copy$, $copy$Drone Inspections$copy$),
  ($copy$quote.drone-inspections.summary$copy$, $copy$A visual record of a roof, solar array, shed, tank or carport, taken from above.$copy$),
  ($copy$quote.drone-inspections.baseLabel$copy$, $copy$Visual inspection$copy$),
  ($copy$quote.drone-inspections.baseDetail$copy$, $copy$Photos and video$copy$),
  ($copy$quote.drone-inspections.basePrice$copy$, $copy$150$copy$),
  ($copy$quote.drone-inspections.overview.0$copy$, $copy$Photographs and video of the area you nominate$copy$),
  ($copy$quote.drone-inspections.overview.1$copy$, $copy$Roofs, solar panels, sheds, tanks and carports$copy$),
  ($copy$quote.drone-inspections.overview.2$copy$, $copy$Visible damage, repairs and maintenance areas$copy$),
  ($copy$quote.drone-inspections.overview.3$copy$, $copy$Completed without unnecessary access at height$copy$),
  ($copy$quote.drone-inspections.finish.type$copy$, $copy$payment$copy$),
  ($copy$quote.drone-inspections.finish.venueLabel$copy$, $copy$Location of the site$copy$),
  ($copy$quote.drone-inspections.finish.venueError$copy$, $copy$site location$copy$),
  ($copy$quote.drone-inspections.finish.dateLabel$copy$, $copy$Date of the inspection$copy$),
  ($copy$quote.drone-inspections.finish.dateError$copy$, $copy$date of the inspection$copy$),
  ($copy$quote.drone-inspections.finish.timeLabel$copy$, $copy$Time we should arrive$copy$),
  ($copy$quote.drone-inspections.finish.messageLabel$copy$, $copy$What should we inspect?$copy$),
  ($copy$quote.drone-inspections.finish.messageHeading$copy$, $copy$What should we inspect?$copy$),
  ($copy$quote.drone-inspections.location.title$copy$, $copy$Location$copy$),
  ($copy$quote.drone-inspections.location.hint$copy$, $copy$Where is the inspection?$copy$),
  ($copy$quote.drone-inspections.location.gladstone.label$copy$, $copy$Gladstone$copy$),
  ($copy$quote.drone-inspections.location.boyne.label$copy$, $copy$Boyne Island / Tannum Sands$copy$),
  ($copy$quote.drone-inspections.location.calliope.label$copy$, $copy$Calliope$copy$),
  ($copy$quote.drone-inspections.location.agnes.label$copy$, $copy$Agnes Water / 1770$copy$),
  ($copy$quote.drone-inspections.location.agnes.price$copy$, $copy$100$copy$),
  ($copy$quote.drone-inspections.location.other.label$copy$, $copy$Other$copy$),
  ($copy$quote.drone-inspections.location.other.inputLabel$copy$, $copy$Location$copy$),
  ($copy$quote.drone-inspections.location.other.note$copy$, $copy$We'll confirm$copy$),
  ($copy$quote.drone-inspections.subject.title$copy$, $copy$Inspection$copy$),
  ($copy$quote.drone-inspections.subject.hint$copy$, $copy$What are we inspecting?$copy$),
  ($copy$quote.drone-inspections.subject.roof.label$copy$, $copy$Roof$copy$),
  ($copy$quote.drone-inspections.subject.solar.label$copy$, $copy$Solar Panels$copy$),
  ($copy$quote.drone-inspections.subject.structure.label$copy$, $copy$Structure$copy$),
  ($copy$quote.drone-inspections.subject.structure.detail$copy$, $copy$Sheds, tanks, carports.$copy$),
  ($copy$quote.drone-inspections.subject.other.label$copy$, $copy$Something Else$copy$),
  ($copy$quote.drone-inspections.subject.other.inputLabel$copy$, $copy$What is it?$copy$),
  ($copy$quote.drone-inspections.subject.other.inputError$copy$, $copy$Tell us what we are inspecting to continue.$copy$),
  ($copy$quote.drone-inspections.subject.other.note$copy$, $copy$Enquire$copy$),
  ($copy$quote.drone-inspections.acknowledgements.title$copy$, $copy$Acknowledgements$copy$),
  ($copy$quote.drone-inspections.acknowledgements.hint$copy$, $copy$Accept each point to continue.$copy$),
  ($copy$quote.drone-inspections.acknowledgements.flight-rules.label$copy$, $copy$Flight Rules & Safety$copy$),
  ($copy$quote.drone-inspections.acknowledgements.flight-rules.detail$copy$, $copy$I understand all drone inspections are subject to CASA regulations, airspace restrictions and the pilot’s safety assessment. These requirements may limit the height, position or angles available when inspecting the site.$copy$),
  ($copy$quote.drone-inspections.acknowledgements.weather.label$copy$, $copy$Weather & Image Quality$copy$),
  ($copy$quote.drone-inspections.acknowledgements.weather.detail$copy$, $copy$I understand weather, wind, lighting and other conditions may affect the images. The inspection may be postponed or rescheduled if conditions are unsafe or unlikely to produce suitable imagery.$copy$),
  ($copy$quote.drone-inspections.acknowledgements.access.label$copy$, $copy$Access & Permission$copy$),
  ($copy$quote.drone-inspections.acknowledgements.access.detail$copy$, $copy$I confirm I have permission for the site to be inspected and for Gladstone Uncovered to access the nominated location where required. I understand neighbouring properties, people, roads, obstacles and other site conditions may restrict the inspection.$copy$),
  ($copy$quote.drone-inspections.acknowledgements.booking.label$copy$, $copy$Booking, Cancellations & Refunds$copy$),
  ($copy$quote.drone-inspections.acknowledgements.booking.detail$copy$, $copy$I understand a 20% deposit is required to confirm the booking and 48 hours’ notice is required for cancellation or rescheduling. Late cancellations may result in loss of the deposit. If the inspection cannot proceed due to weather, safety, legal restrictions or unsuitable conditions, the service may be rescheduled or refunded where appropriate.$copy$),
  ($copy$quote.event-highlights.title$copy$, $copy$Event Highlights$copy$),
  ($copy$quote.event-highlights.summary$copy$, $copy$One edited film of your event, covering the people, the atmosphere and the moments worth keeping.$copy$),
  ($copy$quote.event-highlights.baseLabel$copy$, $copy$Event Highlights base package$copy$),
  ($copy$quote.event-highlights.baseDetail$copy$, $copy$Up to 2 hours$copy$),
  ($copy$quote.event-highlights.basePrice$copy$, $copy$400$copy$),
  ($copy$quote.event-highlights.overview.0$copy$, $copy$Up to 2 hours on site with a two-person crew$copy$),
  ($copy$quote.event-highlights.overview.1$copy$, $copy$Ground coverage and one drone flight$copy$),
  ($copy$quote.event-highlights.overview.2$copy$, $copy$Professional editing$copy$),
  ($copy$quote.event-highlights.overview.3$copy$, $copy$One social highlight, approximately 30–90 seconds$copy$),
  ($copy$quote.event-highlights.finish.type$copy$, $copy$payment$copy$),
  ($copy$quote.event-highlights.finish.venueLabel$copy$, $copy$Location of the event$copy$),
  ($copy$quote.event-highlights.finish.venueError$copy$, $copy$event location$copy$),
  ($copy$quote.event-highlights.finish.dateLabel$copy$, $copy$Date of event$copy$),
  ($copy$quote.event-highlights.finish.dateError$copy$, $copy$date of event$copy$),
  ($copy$quote.event-highlights.finish.timeLabel$copy$, $copy$Time we should arrive$copy$),
  ($copy$quote.event-highlights.finish.messageLabel$copy$, $copy$Tell us about the event$copy$),
  ($copy$quote.event-highlights.finish.messageHeading$copy$, $copy$The event:$copy$),
  ($copy$quote.event-highlights.location.title$copy$, $copy$Location$copy$),
  ($copy$quote.event-highlights.location.hint$copy$, $copy$Where is the event?$copy$),
  ($copy$quote.event-highlights.location.gladstone.label$copy$, $copy$Gladstone$copy$),
  ($copy$quote.event-highlights.location.boyne.label$copy$, $copy$Boyne Island / Tannum Sands$copy$),
  ($copy$quote.event-highlights.location.calliope.label$copy$, $copy$Calliope$copy$),
  ($copy$quote.event-highlights.location.greater.label$copy$, $copy$Greater Gladstone Region$copy$),
  ($copy$quote.event-highlights.location.greater.price$copy$, $copy$100$copy$),
  ($copy$quote.event-highlights.location.outside.label$copy$, $copy$Outside The Gladstone Region$copy$),
  ($copy$quote.event-highlights.location.outside.inputLabel$copy$, $copy$Location$copy$),
  ($copy$quote.event-highlights.location.outside.note$copy$, $copy$Contact us$copy$),
  ($copy$quote.event-highlights.event.title$copy$, $copy$Event type$copy$),
  ($copy$quote.event-highlights.event.hint$copy$, $copy$What kind of event is it?$copy$),
  ($copy$quote.event-highlights.event.celebrations.label$copy$, $copy$Celebrations$copy$),
  ($copy$quote.event-highlights.event.celebrations.detail$copy$, $copy$Christmas parties, ladies days, birthdays, formals, private functions, corporate celebrations and similar events.$copy$),
  ($copy$quote.event-highlights.event.sport.label$copy$, $copy$Sport$copy$),
  ($copy$quote.event-highlights.event.sport.detail$copy$, $copy$Football games, sporting carnivals, fun runs, motorsports, competitions and similar sporting events.$copy$),
  ($copy$quote.event-highlights.event.community.label$copy$, $copy$Community Events$copy$),
  ($copy$quote.event-highlights.event.community.detail$copy$, $copy$Markets, shows and fairs, horse races, festivals and other community events.$copy$),
  ($copy$quote.event-highlights.event.other.label$copy$, $copy$Something Else$copy$),
  ($copy$quote.event-highlights.event.other.inputLabel$copy$, $copy$What is it?$copy$),
  ($copy$quote.event-highlights.event.other.inputError$copy$, $copy$Tell us what the event is to continue.$copy$),
  ($copy$quote.event-highlights.event.other.note$copy$, $copy$Enquire$copy$),
  ($copy$quote.event-highlights.addons.title$copy$, $copy$Add-ons$copy$),
  ($copy$quote.event-highlights.addons.hint$copy$, $copy$Optional. Removing the drone and adding another flight can’t be combined.$copy$),
  ($copy$quote.event-highlights.addons.extra-video.label$copy$, $copy$Additional Highlight Video$copy$),
  ($copy$quote.event-highlights.addons.extra-video.detail$copy$, $copy$Another professionally edited highlight from the event footage.$copy$),
  ($copy$quote.event-highlights.addons.extra-video.price$copy$, $copy$125$copy$),
  ($copy$quote.event-highlights.addons.extend-crew.label$copy$, $copy$Extend Ground Crew$copy$),
  ($copy$quote.event-highlights.addons.extend-crew.detail$copy$, $copy$One additional hour of ground coverage.$copy$),
  ($copy$quote.event-highlights.addons.extend-crew.price$copy$, $copy$125$copy$),
  ($copy$quote.event-highlights.addons.extra-flight.label$copy$, $copy$Additional Drone Flight$copy$),
  ($copy$quote.event-highlights.addons.extra-flight.detail$copy$, $copy$About 25 minutes, subject to flight conditions and CASA requirements.$copy$),
  ($copy$quote.event-highlights.addons.extra-flight.price$copy$, $copy$50$copy$),
  ($copy$quote.event-highlights.addons.catalogue.label$copy$, $copy$Unedited Video Catalogue$copy$),
  ($copy$quote.event-highlights.addons.catalogue.detail$copy$, $copy$At least 10 additional unedited clips from the event.$copy$),
  ($copy$quote.event-highlights.addons.catalogue.price$copy$, $copy$100$copy$),
  ($copy$quote.event-highlights.addons.no-drone.label$copy$, $copy$Drone Footage Not Required$copy$),
  ($copy$quote.event-highlights.addons.no-drone.detail$copy$, $copy$Remove aerial coverage from the package.$copy$),
  ($copy$quote.event-highlights.addons.no-drone.price$copy$, $copy$-50$copy$),
  ($copy$quote.event-highlights.acknowledgements.title$copy$, $copy$Before you book$copy$),
  ($copy$quote.event-highlights.acknowledgements.hint$copy$, $copy$Accept each point to continue.$copy$),
  ($copy$quote.event-highlights.acknowledgements.permissions.label$copy$, $copy$Filming & Permissions$copy$),
  ($copy$quote.event-highlights.acknowledgements.permissions.detail$copy$, $copy$I confirm I have authority to arrange filming at the event and understand that guests, participants and event activities may be captured. Where required, I am responsible for obtaining appropriate permissions from the venue, event organiser and participants.$copy$),
  ($copy$quote.event-highlights.acknowledgements.drone-rules.label$copy$, $copy$Drone Rules & Safety$copy$),
  ($copy$quote.event-highlights.acknowledgements.drone-rules.detail$copy$, $copy$I understand all drone operations are subject to CASA regulations, airspace restrictions, crowds, site conditions and the pilot’s safety assessment. These requirements may restrict or prevent drone coverage.$copy$),
  ($copy$quote.event-highlights.acknowledgements.coverage.label$copy$, $copy$Coverage & Final Video$copy$),
  ($copy$quote.event-highlights.acknowledgements.coverage.detail$copy$, $copy$I understand Event Highlights captures selected moments rather than continuous event coverage. The standard package includes approximately one hour of ground coverage, one drone flight and one professionally edited 30–90 second highlight video. Specific people, moments or shots cannot be guaranteed unless agreed beforehand.$copy$),
  ($copy$quote.event-highlights.acknowledgements.changes.label$copy$, $copy$Weather, Changes & Cancellations$copy$),
  ($copy$quote.event-highlights.acknowledgements.changes.detail$copy$, $copy$I understand weather, lighting and event conditions may affect coverage or footage quality. A 20% deposit is required to confirm the booking and 48 hours’ notice is required for cancellation or rescheduling. Late cancellations may result in loss of the deposit. Where Gladstone Uncovered cannot safely or reasonably provide the service, rescheduling or a refund may be offered where appropriate.$copy$),
  ($copy$quote.full-day-event-coverage.title$copy$, $copy$Full Day Event Coverage$copy$),
  ($copy$quote.full-day-event-coverage.summary$copy$, $copy$Longer coverage with a two-person crew, three edited reels and a catalogue of extra clips.$copy$),
  ($copy$quote.full-day-event-coverage.baseLabel$copy$, $copy$Full Day Event Coverage base package$copy$),
  ($copy$quote.full-day-event-coverage.baseDetail$copy$, $copy$Up to 5 hours$copy$),
  ($copy$quote.full-day-event-coverage.basePrice$copy$, $copy$900$copy$),
  ($copy$quote.full-day-event-coverage.overview.0$copy$, $copy$Up to 5 hours with a two-person crew$copy$),
  ($copy$quote.full-day-event-coverage.overview.1$copy$, $copy$Ground filming and up to 3 drone flights$copy$),
  ($copy$quote.full-day-event-coverage.overview.2$copy$, $copy$3 professionally edited social reels$copy$),
  ($copy$quote.full-day-event-coverage.overview.3$copy$, $copy$A catalogue of additional unedited clips$copy$),
  ($copy$quote.full-day-event-coverage.finish.type$copy$, $copy$payment$copy$),
  ($copy$quote.full-day-event-coverage.finish.venueLabel$copy$, $copy$Location of the event$copy$),
  ($copy$quote.full-day-event-coverage.finish.venueError$copy$, $copy$event location$copy$),
  ($copy$quote.full-day-event-coverage.finish.dateLabel$copy$, $copy$Date of event$copy$),
  ($copy$quote.full-day-event-coverage.finish.dateError$copy$, $copy$date of event$copy$),
  ($copy$quote.full-day-event-coverage.finish.timeLabel$copy$, $copy$Time we should arrive$copy$),
  ($copy$quote.full-day-event-coverage.finish.messageLabel$copy$, $copy$Tell us about the event$copy$),
  ($copy$quote.full-day-event-coverage.finish.messageHeading$copy$, $copy$The event:$copy$),
  ($copy$quote.full-day-event-coverage.location.title$copy$, $copy$Location$copy$),
  ($copy$quote.full-day-event-coverage.location.hint$copy$, $copy$Where is the event?$copy$),
  ($copy$quote.full-day-event-coverage.location.gladstone.label$copy$, $copy$Gladstone$copy$),
  ($copy$quote.full-day-event-coverage.location.boyne.label$copy$, $copy$Boyne Island / Tannum Sands$copy$),
  ($copy$quote.full-day-event-coverage.location.calliope.label$copy$, $copy$Calliope$copy$),
  ($copy$quote.full-day-event-coverage.location.greater.label$copy$, $copy$Greater Gladstone Region$copy$),
  ($copy$quote.full-day-event-coverage.location.greater.price$copy$, $copy$100$copy$),
  ($copy$quote.full-day-event-coverage.location.outside.label$copy$, $copy$Outside The Gladstone Region$copy$),
  ($copy$quote.full-day-event-coverage.location.outside.inputLabel$copy$, $copy$Location$copy$),
  ($copy$quote.full-day-event-coverage.location.outside.note$copy$, $copy$Contact us$copy$),
  ($copy$quote.full-day-event-coverage.event.title$copy$, $copy$Event type$copy$),
  ($copy$quote.full-day-event-coverage.event.hint$copy$, $copy$What kind of event is it?$copy$),
  ($copy$quote.full-day-event-coverage.event.celebrations.label$copy$, $copy$Celebrations$copy$),
  ($copy$quote.full-day-event-coverage.event.celebrations.detail$copy$, $copy$Christmas parties, ladies days, birthdays, formals, corporate celebrations and large private functions.$copy$),
  ($copy$quote.full-day-event-coverage.event.sport.label$copy$, $copy$Sport$copy$),
  ($copy$quote.full-day-event-coverage.event.sport.detail$copy$, $copy$Football, sporting carnivals, fun runs, motorsports, competitions and other sporting events.$copy$),
  ($copy$quote.full-day-event-coverage.event.community.label$copy$, $copy$Community Events$copy$),
  ($copy$quote.full-day-event-coverage.event.community.detail$copy$, $copy$Markets, shows and fairs, horse races, festivals and other community events.$copy$),
  ($copy$quote.full-day-event-coverage.event.other.label$copy$, $copy$Something Else$copy$),
  ($copy$quote.full-day-event-coverage.event.other.inputLabel$copy$, $copy$What is it?$copy$),
  ($copy$quote.full-day-event-coverage.event.other.inputError$copy$, $copy$Tell us what the event is to continue.$copy$),
  ($copy$quote.full-day-event-coverage.event.other.note$copy$, $copy$Enquire$copy$),
  ($copy$quote.full-day-event-coverage.addons.title$copy$, $copy$Add-ons$copy$),
  ($copy$quote.full-day-event-coverage.addons.hint$copy$, $copy$Optional. Use the count when you need more than one.$copy$),
  ($copy$quote.full-day-event-coverage.addons.extra-reel.label$copy$, $copy$Additional Highlight Reel$copy$),
  ($copy$quote.full-day-event-coverage.addons.extra-reel.detail$copy$, $copy$Another professionally edited 30–90 second reel, on top of the three included.$copy$),
  ($copy$quote.full-day-event-coverage.addons.extra-reel.price$copy$, $copy$125$copy$),
  ($copy$quote.full-day-event-coverage.addons.extra-hours.label$copy$, $copy$Additional Coverage$copy$),
  ($copy$quote.full-day-event-coverage.addons.extra-hours.detail$copy$, $copy$Extend the two-person ground crew beyond the included 5 hours.$copy$),
  ($copy$quote.full-day-event-coverage.addons.extra-hours.price$copy$, $copy$125$copy$),
  ($copy$quote.full-day-event-coverage.addons.extra-flight.label$copy$, $copy$Additional Drone Flight$copy$),
  ($copy$quote.full-day-event-coverage.addons.extra-flight.detail$copy$, $copy$About 25 minutes, subject to CASA requirements, weather and operating conditions.$copy$),
  ($copy$quote.full-day-event-coverage.addons.extra-flight.price$copy$, $copy$50$copy$),
  ($copy$quote.full-day-event-coverage.live.title$copy$, $copy$Live content$copy$),
  ($copy$quote.full-day-event-coverage.live.hint$copy$, $copy$Optional. Each live edited reel is delivered during the event and uses one of the three included reels. It changes when that reel is delivered, rather than adding another reel. Example: 1 live edited reel means 1 reel during the event and 2 after. A live basic video does not use one of those reels.$copy$),
  ($copy$quote.full-day-event-coverage.live.live-reel.label$copy$, $copy$Live Edited Reel$copy$),
  ($copy$quote.full-day-event-coverage.live.live-reel.detail$copy$, $copy$A professionally edited video prepared and delivered during the event for immediate social media use. Up to 3, one for each included reel.$copy$),
  ($copy$quote.full-day-event-coverage.live.live-reel.price$copy$, $copy$125$copy$),
  ($copy$quote.full-day-event-coverage.live.live-basic.label$copy$, $copy$Live Basic Video$copy$),
  ($copy$quote.full-day-event-coverage.live.live-basic.detail$copy$, $copy$A basic unedited video prepared and supplied during the event. This does not use one of the three edited reels.$copy$),
  ($copy$quote.full-day-event-coverage.live.live-basic.price$copy$, $copy$75$copy$),
  ($copy$quote.full-day-event-coverage.acknowledgements.title$copy$, $copy$Before you book$copy$),
  ($copy$quote.full-day-event-coverage.acknowledgements.hint$copy$, $copy$Accept each point to continue.$copy$),
  ($copy$quote.full-day-event-coverage.acknowledgements.permissions.label$copy$, $copy$Filming & Permissions$copy$),
  ($copy$quote.full-day-event-coverage.acknowledgements.permissions.detail$copy$, $copy$I confirm I have authority to arrange filming at the event and understand guests, participants and event activities may be captured. Where required, I am responsible for obtaining appropriate permissions from the venue, event organiser and participants.$copy$),
  ($copy$quote.full-day-event-coverage.acknowledgements.drone-rules.label$copy$, $copy$Drone Rules & Safety$copy$),
  ($copy$quote.full-day-event-coverage.acknowledgements.drone-rules.detail$copy$, $copy$I understand drone operations are subject to CASA regulations, airspace restrictions, crowds, weather, site conditions and the pilot’s safety assessment. These requirements may restrict or prevent some or all planned drone flights.$copy$),
  ($copy$quote.full-day-event-coverage.acknowledgements.coverage.label$copy$, $copy$Coverage & Deliverables$copy$),
  ($copy$quote.full-day-event-coverage.acknowledgements.coverage.detail$copy$, $copy$I understand Full Day Event Coverage captures selected moments throughout the event rather than continuous recording. The package includes up to 5 hours of coverage, up to three drone flights, three professionally edited social media reels and a catalogue of additional unedited footage. Specific people, moments or shots cannot be guaranteed unless agreed beforehand.$copy$),
  ($copy$quote.full-day-event-coverage.acknowledgements.changes.label$copy$, $copy$Weather, Changes & Cancellations$copy$),
  ($copy$quote.full-day-event-coverage.acknowledgements.changes.detail$copy$, $copy$I understand weather, lighting and event conditions may affect coverage or footage quality. A 20% deposit is required to confirm the booking and 48 hours’ notice is required for cancellation or rescheduling. Late cancellations may result in loss of the deposit. Where Gladstone Uncovered cannot safely or reasonably provide the service, rescheduling or a refund may be offered where appropriate.$copy$)
on conflict (key) do nothing;
